### PR TITLE
CMake: Include only the libraries required

### PR DESCRIPTION
**Pull request by hugueskamba**
Mbed OS now handles the dependencies.

Reviewers:
@0xc0170 @LDong-Arm @rajkan01

### CODE REVIEW

**Review by rajkan01 — APPROVED** [review]
LGTM

**Review by 0xc0170 — APPROVED** [review]
One question: does a user need to request littlefs in sd-example?  I assume so as we do not provide default and then a way to replace it?

**Comment by 0xc0170** [comment]
`#include "LittleFileSystem.h"` in the main.cpp answers my question :-) we do need it.

**Comment by 0xc0170** [comment]
As this is simple fix to CMakelists, I'll merge it.

**Pull request merged**
